### ISSUE TITLE
Support local setup running on Mac environment

### ISSUE THREAD

**Issue by arunneoz** [fusor/catasb#42]
Hi,

I created a local directory on my Mac for persistedvolumes and added it to the Docker Preferences. 

2. I set the Cluster ip to 127.0.0.1

3. When i ran the installation , iam getting the following error,

What am i missing. If i run oc cluster up the cluster is starting normally.

TASK [openshift_setup : debug] ***********************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "oc_cluster_up_first_run = False, oc_cluster_status.stdout = 'The OpenShift cluster was started 6 minutes ago\n\nWeb console URL: https://localhost:8443\n\nConfig is at host directory /var/lib/origin/openshift.local.config\nVolumes are at host directory /var/lib/origin/openshift.local.volumes\nPersistent volumes are at host directory /persistedvolumes\nData will be discarded when cluster is destroyed'"
}

TASK [openshift_setup : Add extension script to oc config to talk to svc catalog] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /var/lib/origin/openshift.local.config does not exist"}
	to retry, use: --limit @/Users/asanthan/Downloads/openshift-origin-client-tools-v1.5.0-031cbe4-mac/catasb/ansible/setup_local_environment.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************

**Comment by jwmatthews** [comment]
Hi @arunneoz thanks for the issue.  We haven't added support for local mode to run on Mac. (though the ec2 mode has been tested on both linux/mac)

As to getting local to run on Mac, we need to add a few tweaks to the ansible code, ie config files need to be modified on the dockermachine VM and not directly on the host as with Linux.  It's something we'd like to do in the near future.

In meantime you can run local mode on Linux if you are interested, or you can ec2 mode from the mac.

**Comment by arunneoz** [comment]
Perfect , this makes sense. I will try in linux.

Regards

Arun

**Comment by jwmatthews** [comment]
I have a first cut of support on macOS for the local setup in the below branch:
https://github.com/fusor/catasb/tree/mac

I've had success with this to do the demo of:
 - Create a new project, 'demo'
 - Provision postgres demo APB from Service Catalog WebUI into 'demo' project
 - Create a python app in 'demo' project with s2i of https://github.com/fusor/awsdemo.git
 - After postgres APB has completed and python app is deployed
 - Create binding on python app to postgres service
 - Reload url for python app see data is populated.

This video walks through a similar flow of what is now working for local mac setup in the branch referenced:
https://www.youtube.com/watch?v=xmd52NhEjCk

**Comment by jwmatthews** [comment]
Closing this issue as local support to run on macOS has been added in PR #49
