### ISSUE TITLE
Note that running local/linux on rhel7 requires 'ifconfig' but it's not always installed by default in el7

### ISSUE THREAD

**Issue by jwmatthews** [fusor/catasb#88]
Need to install 'net-tools' on el7 if we want to rely on 'ifconfig' in
https://github.com/fusor/catasb/blob/dev/config/linux_env_vars#L1

**Comment by jmrodri** [comment]
I was always told to use `ip` instead of `ifconfig`.

**Comment by jmrodri** [comment]
```
export PUBLIC_IP="$(ip addr show dev docker0 | grep 'inet ' | awk '{print $2}' | sed 's/\/[0-9]*//')"
```

**Comment by jwmatthews** [comment]
Switched to:

export PUBLIC_IP="$(ip addr show docker0 | grep -Po 'inet \K[\d.]+')"

As part of 
https://github.com/fusor/catasb/pull/99
