### ISSUE TITLE
Unable to register existing brokers

### ISSUE THREAD

**Issue by charliejllewellyn** [fusor/catasb#89]
When I register a new external broker it errors getting the catalog. The error is:

`I0716 08:59:19.549125       1 event.go:217] Event(v1.ObjectReference{Kind:"Broker", Namespace:"", Name:"anynines-postgres", UID:"74e8215f-69fb-11e7-a06d-0242ac110003", APIVersion:"servicecatalog.k8s.io", ResourceVersion:"45", FieldPath:""}): type: 'Warning' reason: 'ErrorFetchingCatalog' Error getting broker catalog for broker "anynines-postgres": Status: 401; ErrorMessage: <nil>; Description: <nil>; ResponseError: invalid character 'H' looking for beginning of value
I0716 08:59:19.550599       1 controller_broker.go:427] Updated ready condition for Broker anynines-postgres to False`

However this worked in a previous release (built on alpha-1). I suspect it no longer passing the authentication details details through correctly. Querying the service catalog for the broker status returns:

`    {
      "metadata": {
        "name": "anynines-postgres",
        "selfLink": "/apis/servicecatalog.k8s.io/v1alpha1/brokersanynines-postgres",
        "uid": "74e8215f-69fb-11e7-a06d-0242ac110003",
        "resourceVersion": "45",
        "creationTimestamp": "2017-07-16T07:50:37Z",
        "finalizers": [
          "kubernetes-incubator/service-catalog"
        ]
      },
      "spec": {
        "url": "http://postgresql-service-broker.service.dc1.consul:3000/"
      },
      "status": {
        "conditions": [
          {
            "type": "Ready",
            "status": "False",
            "lastTransitionTime": "2017-07-16T07:50:37Z",
            "reason": "ErrorFetchingCatalog",
            "message": "Error fetching catalog. Error getting broker catalog for broker \"anynines-postgres\": Status: 401; ErrorMessage: \u003cnil\u003e; Description: \u003cnil\u003e; ResponseError: invalid character 'H' looking for beginning of value"
          }` 

Notice the spec contains no authentication details. However on a previous release version I get which does correctly contain a reference to the authentication details.

`    {
      "metadata": {
        "name": "anynines-postgres",
        "selfLink": "/apis/servicecatalog.k8s.io/v1alpha1/brokersanynines-postgres",
        "uid": "e32c6982-6877-11e7-9e6a-0242ac110002",
        "resourceVersion": "28",
        "creationTimestamp": "2017-07-14T09:36:17Z",
        "finalizers": [
          "kubernetes"
        ]
      },
      "spec": {
        "url": "http://postgresql-service-broker.service.dc1.consul:3000/",
        "authSecret": {
          "namespace": "openshift",
          "name": "anynines-secret"
        }
      },
      "status": {
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastTransitionTime": "2017-07-14T09:36:18Z",
            "reason": "FetchedCatalog",
            "message": "Successfully fetched catalog entries from broker."
          }
        ]
      }
    }`

Any help would be much appreciated.

**Comment by jwmatthews** [comment]
@charliejllewellyn we have not hit this issue ourselves yet.  This sprint we are adding authentication into the Ansible Service Broker, perhaps at that point we may run into this.  @jmrodri @shawn-hurley if you guys run into this issue during adding auth/ssl testing, please add a comment to help @charliejllewellyn 

I recommend filing an issue in the service-catalog:
 https://github.com/kubernetes-incubator/service-catalog/issues

Or asking in https://kubernetes.slack.com  #sig-service-catalog

**Comment by charliejllewellyn** [comment]
No worries. In case it helps I worked it out. The spec changed between the releases of the catalog. I was passing:

`apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: postgres
spec:
  url: http://postgresql-service-broker.service.dc1.consul:3000/
  authSecret:
    name: "postgres-secret"
    namespace: "openshift"`

And now pass:

`apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: postgres
spec:
  url: http://postgresql-service-broker.service.dc1.consul:3000/
  authInfo:
     basicAuthSecret:
       name: "postgres-secret"
       namespace: "openshift"`
