### ISSUE TITLE
shouldn't default to anyuid scc

### ISSUE THREAD

**Issue by tchughesiv** [fusor/catasb#91]
Currently, during catasb setup, it appears that all authenticated users are being given anyuid scc rights.
https://github.com/fusor/catasb/blob/3ba823a7a4042f4ed256218db4f288abb86be74f/ansible/roles/openshift_setup/tasks/main.yml#L340

I assume this is to provide a more pleasant experience for devs, but it's not how openshift runs by default and could prove problematic when an apb makes the transition to openshift online/dedicated/etc.  Images execting to run as a certain uid, root or otherwise, could error out.

Maybe, instead, we add an scc option to the apb.yml spec and allow for a dev to ask the broker for a certain scc allocated to a certain sa in a specific project, but keep the defaults as is?

We can drive some of this work if folks are agreeable to it...

**Comment by codificat** [comment]
I agree that running without special permissions by default should help expose potential issues in the APBs.

As an example: I just ran a provision of the current rhscl-postgresql-apb on an environment without anyuid access and it fails in the task that stores the generated credentials:

```
TASK [rhscl-postgresql-apb-openshift : copy] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "e3a28f79922c1e4525d97519c2e7209584d45e29", "failed": true, "msg": "Destination /etc/apb not writable"}
```

That APB does not really need any special privileges and should be able to run under a restricted SCC - we'd just need to store the temporary credentials file in a writable destination.

**Comment by rflorenc** [comment]
+1
Makes sense to have this as a configurable knob.

**Comment by jwmatthews** [comment]
Makes sense, aligned to the sprint in trello.
https://trello.com/c/8Dn0cyCZ
